"""Add categories_no_shipping to admin_settings

Revision ID: 620a451acbc9
Revises: 001_admin_settings
Create Date: 2025-12-07 01:28:28.031961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620a451acbc9'
down_revision: Union[str, None] = '001_admin_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar columna nullable primero
    op.add_column('admin_settings', sa.Column('categories_no_shipping', sa.JSON(), nullable=True))
    # Establecer valor por defecto
    op.execute("UPDATE admin_settings SET categories_no_shipping = '[]'")
    # Hacer la columna NOT NULL
    op.alter_column('admin_settings', 'categories_no_shipping', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_settings', 'categories_no_shipping')
    # ### end Alembic commands ###
