"""protocols_category_func

Revision ID: d5f25d66e2a1
Revises: 26e7a89ef74f
Create Date: 2026-05-22 01:45:11.544497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f25d66e2a1'
down_revision: Union[str, None] = '26e7a89ef74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('protocol_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_categories_id'), 'protocol_categories', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_categories_name'), 'protocol_categories', ['name'], unique=True)
    op.create_index(op.f('ix_protocol_categories_slug'), 'protocol_categories', ['slug'], unique=True)

    # 1. Insertar una categoría por defecto para asignar a los protocolos existentes
    op.execute("""
        INSERT INTO protocol_categories (name, slug, is_active, created_at)
        VALUES ('General', 'general', true, now())
    """)

    # 2. Agregar la columna como nullable primero
    op.add_column('protocols', sa.Column('category_id', sa.Integer(), nullable=True))

    # 3. Asignar la categoría por defecto a todos los registros existentes
    op.execute("""
        UPDATE protocols SET category_id = (
            SELECT id FROM protocol_categories WHERE slug = 'general'
        )
    """)

    # 4. Ahora sí aplicar NOT NULL
    op.alter_column('protocols', 'category_id', nullable=False)

    op.create_index(op.f('ix_protocols_category_id'), 'protocols', ['category_id'], unique=False)
    op.create_foreign_key(None, 'protocols', 'protocol_categories', ['category_id'], ['id'])
    op.drop_column('protocols', 'difficulty_level')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('difficulty_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'protocols', type_='foreignkey')
    op.drop_index(op.f('ix_protocols_category_id'), table_name='protocols')
    op.drop_column('protocols', 'category_id')
    op.drop_index(op.f('ix_protocol_categories_slug'), table_name='protocol_categories')
    op.drop_index(op.f('ix_protocol_categories_name'), table_name='protocol_categories')
    op.drop_index(op.f('ix_protocol_categories_id'), table_name='protocol_categories')
    op.drop_table('protocol_categories')
    # ### end Alembic commands ###
