"""protocol_own_price_associated_products

Revision ID: 26e7a89ef74f
Revises: 99142cd437e7
Create Date: 2026-05-21 01:31:16.220860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e7a89ef74f'
down_revision: Union[str, None] = '99142cd437e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_products',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('protocol_id', 'product_id')
    )
    op.add_column('protocols', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE protocols SET price = 0.00 WHERE price IS NULL")
    op.alter_column('protocols', 'price', nullable=False)
    op.add_column('protocols', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'image_url')
    op.drop_column('protocols', 'price')
    op.drop_table('protocol_products')
    # ### end Alembic commands ###
