"""protocols_digital_products

Revision ID: 99142cd437e7
Revises: d2cf49863bab
Create Date: 2026-05-20 20:06:02.596201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99142cd437e7'
down_revision: Union[str, None] = 'd2cf49863bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_id'), 'protocols', ['id'], unique=False)
    op.create_index(op.f('ix_protocols_name'), 'protocols', ['name'], unique=False)
    op.create_index(op.f('ix_protocols_product_id'), 'protocols', ['product_id'], unique=True)
    op.create_index(op.f('ix_protocols_slug'), 'protocols', ['slug'], unique=True)
    op.create_table('protocol_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'slug', name='uq_phase_protocol_slug')
    )
    op.create_index(op.f('ix_protocol_phases_id'), 'protocol_phases', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_phases_protocol_id'), 'protocol_phases', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_protocol_phases_slug'), 'protocol_phases', ['slug'], unique=False)
    op.create_table('protocol_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_phase_order', sa.Integer(), nullable=True),
    sa.Column('completed_phases', sa.Integer(), nullable=True),
    sa.Column('total_phases', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_progress_id'), 'protocol_progress', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_progress_protocol_id'), 'protocol_progress', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_protocol_progress_user_id'), 'protocol_progress', ['user_id'], unique=False)
    op.create_table('protocol_accesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('access_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_accesses_id'), 'protocol_accesses', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_accesses_order_id'), 'protocol_accesses', ['order_id'], unique=False)
    op.create_index(op.f('ix_protocol_accesses_order_item_id'), 'protocol_accesses', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_protocol_accesses_protocol_id'), 'protocol_accesses', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_protocol_accesses_user_id'), 'protocol_accesses', ['user_id'], unique=False)
    op.create_table('protocol_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['protocol_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_resources_id'), 'protocol_resources', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_resources_phase_id'), 'protocol_resources', ['phase_id'], unique=False)
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('products', sa.Column('is_digital', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_digital')
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_protocol_resources_phase_id'), table_name='protocol_resources')
    op.drop_index(op.f('ix_protocol_resources_id'), table_name='protocol_resources')
    op.drop_table('protocol_resources')
    op.drop_index(op.f('ix_protocol_accesses_user_id'), table_name='protocol_accesses')
    op.drop_index(op.f('ix_protocol_accesses_protocol_id'), table_name='protocol_accesses')
    op.drop_index(op.f('ix_protocol_accesses_order_item_id'), table_name='protocol_accesses')
    op.drop_index(op.f('ix_protocol_accesses_order_id'), table_name='protocol_accesses')
    op.drop_index(op.f('ix_protocol_accesses_id'), table_name='protocol_accesses')
    op.drop_table('protocol_accesses')
    op.drop_index(op.f('ix_protocol_progress_user_id'), table_name='protocol_progress')
    op.drop_index(op.f('ix_protocol_progress_protocol_id'), table_name='protocol_progress')
    op.drop_index(op.f('ix_protocol_progress_id'), table_name='protocol_progress')
    op.drop_table('protocol_progress')
    op.drop_index(op.f('ix_protocol_phases_slug'), table_name='protocol_phases')
    op.drop_index(op.f('ix_protocol_phases_protocol_id'), table_name='protocol_phases')
    op.drop_index(op.f('ix_protocol_phases_id'), table_name='protocol_phases')
    op.drop_table('protocol_phases')
    op.drop_index(op.f('ix_protocols_slug'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_product_id'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_name'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_id'), table_name='protocols')
    op.drop_table('protocols')
    # ### end Alembic commands ###
